version: "3.8"

services:
  dbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: dbeaver
    ports:
      - "8087:8978"
    volumes:
      - ./db:/opt/cloudbeaver/workspace
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.dbeaver-secure.rule=Host(`cloudbeaver.local.rutvik.qzz.io`)
      - traefik.http.routers.dbeaver-secure.entrypoints=https
      - traefik.http.routers.dbeaver-secure.tls=true
      - traefik.http.routers.dbeaver-secure.service=dbeaver
      - traefik.http.services.dbeaver.loadbalancer.server.port=8978
      - traefik.http.routers.dbeaver-secure.tls.certresolver=cloudflare

networks:
  proxy:
    external: true

